# Site settings
title: Knowledge Graph Engineering Project
email:
description: 
baseurl: "" # the subpath of your site, e.g. /knowledgegraph/
url: "zehrakorkusuz.github.io" 

twitter_username:
github_username: zehrakorkusuz

# Build settings
markdown: kramdown
